- name: "load migration status from https://memstash.io/ and revert migration if necessary"
  shell: |
    MIGRATION_STATUS=$(curl -H "token: raj01" --request GET https://api.memstash.io/values/migration_status)
    echo ${MIGRATION_STATUS}
    if [[ ${MIGRATION_STATUS} == 1 ]]
    then
      cd /home/ubuntu/backend
      npm run migrations:revert
    fi
  register: revert_migration_output

- debug:
    msg: "{{ revert_migration_output.stdout_lines }}"